apiVersion: v2
name: multi-tenant-mesh
description: A Helm chart for managing multi-tenant environments in service mesh
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: istio-base
    version: "1.18.0"
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: "1.18.0"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled
