{{- range .Values.tenants }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    istio-injection: enabled
    tenant: {{ .name }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
