{{- range .Values.tenants }}
{{- if .networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tenant-isolation
  namespace: {{ .name }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tenant: {{ .name }}
    - namespaceSelector:
        matchLabels:
          istio-injection: enabled
      podSelector:
        matchLabels:
          app: istiod
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          tenant: {{ .name }}
    - namespaceSelector:
        matchLabels:
          istio-injection: enabled
{{- end }}
{{- end }}
