{{- if .Values.resourceQuotas.enabled }}
{{- range .Values.tenants }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ .name }}
spec:
  hard:
    {{- with $.Values.resourceQuotas.default }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
